### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by laokiea** [ihmily/image-matting#1]
2024-01-31 16:25:50.613594: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
When I clicked the upload button, I got the log above.

**Comment by ihmily** [comment]
If you see this prompt, don't worry, it does not affect your operation. If clicking the button does not initiate the matting process, and the program exits unexpectedly, it might be due to insufficient CPU memory. Please free up enough memory and try again.
