### ISSUE TITLE
使用第一种方式时，按住依赖时报错，导致无法运行

### ISSUE THREAD

**Issue by zengxianghui93** [ihmily/image-matting#3]
![image](https://github.com/ihmily/image-matting/assets/17396286/bbc6ac46-fe95-43da-a57b-1f6976446ec0)

感觉像是没找到这几个引用
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.outputs import OutputKeys

**Comment by ihmily** [comment]
Python版本是3.10吗？我这3.10是正常的 ，最好在虚拟环境下安装，不然可能会依赖冲突。

**Comment by zengxianghui93** [comment]
@ihmily OK，我的是Python 3.12.2，我切换成3.10试试。
